package com.hung.auction.domain2;

import java.io.Serializable;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@Table(name = "SINGLE_TABLE_ANIMAL") // had to duplicate this annotation in subclasses otherwise default table name = class name
@DiscriminatorColumn(name = "SINGLE_TABLE_ANIMAL_TYPE", discriminatorType = DiscriminatorType.STRING) // had to duplicate this annotation in subclasses otherwise no discriminator column was generated by Hibernate Tools SchemaExport
@DiscriminatorValue("CAT")
public class SingleTableCat extends SingleTableAnimal implements Serializable {
    public SingleTableCat() {}
    public SingleTableCat(String name) {
        this.setName(name);
    }
}